name: "Builds"

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - master
      - releases/*

jobs:
  build-windows-dotnet:
    name: Build dotnet on windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag dpteam/dotnet:$(date +%s)
      - name: Run the Docker image
        run: docker run --rm dpteam/dotnet --version

  build-windows-msbuild:
    name: Build msbuild on windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile.msbuild --tag dpteam/msbuild:$(date +%s)
      - name: Run the Docker image
        run: docker run --rm dpteam/msbuild --version
